--[[
	Auto Turtle Warrior - Player/Trinkets
	Auto-generated by scripts/extract_trinkets.py from Zebouski/WarriorSim-TurtleWoW.
	DO NOT edit by hand — re-run the script to regenerate.
]]--

ATW.TrinketDB = {
	["Badge of the Swarmguard"] = {
		itemId = 21670,
		category = "onuse",
		onuse = {
			duration = 30,
			cooldown = 180,
			proc = {
				ppm = 10,
				armorPen = 200,
				maxStacks = 6,
			},
		},
		priority = 60,
		respectsSharedCD = true,
	},
	["Diamond Flask"] = {
		itemId = 20130,
		category = "onuse",
		onuse = {
			duration = 60,
			cooldown = 360,
			buff = {
				str = 75,
			},
		},
		priority = 60,
		respectsSharedCD = true,
	},
	["Earthstrike"] = {
		itemId = 21180,
		category = "onuse",
		onuse = {
			duration = 20,
			cooldown = 120,
			buff = {
				ap = 280,
			},
		},
		priority = 65,
		respectsSharedCD = true,
	},
	["Jom Gabbar"] = {
		itemId = 23570,
		category = "onuse",
		onuse = {
			duration = 20,
			cooldown = 120,
			buff = {
				ap = 65,
			},
			stacking = {
				tickInterval = 2,
				maxStacks = 10,
			},
		},
		priority = 65,
		respectsSharedCD = true,
	},
	["Zandalarian Hero Charm"] = {
		itemId = 19950,
		category = "onuse",
		onuse = {
			duration = 20,
			cooldown = 120,
			buff = {
				dmgmod = 40,
			},
			decay = {
				perProc = 2,
				minValue = 0,
			},
		},
		priority = 70,
		respectsSharedCD = true,
	},
	["Kiss of the Spider"] = {
		itemId = 22954,
		category = "onuse_with_passive",
		onuse = {
			duration = 15,
			cooldown = 120,
			multBuff = {
				haste = 20,
			},
		},
		priority = 70,
		respectsSharedCD = true,
		passive = {
			crit = 1,
			hit = 1,
		},
	},
	["Slayer's Crest"] = {
		itemId = 23041,
		category = "onuse_with_passive",
		onuse = {
			duration = 20,
			cooldown = 120,
			buff = {
				ap = 260,
			},
		},
		priority = 65,
		respectsSharedCD = true,
		passive = {
			ap = 64,
		},
	},
	["Banner of the Scarlet Crusade"] = {
		itemId = 84006,
		category = "passive",
		passive = {
			ap = 30,
			haste = 4,
		},
	},
	["Blackhand's Breadth"] = {
		itemId = 13965,
		category = "passive",
		passive = {
			crit = 2,
		},
	},
	["Boon of Niremius"] = {
		itemId = 61095,
		category = "passive",
		passive = {
			haste = 2,
		},
	},
	["Chimaera's Eye"] = {
		itemId = 61517,
		category = "passive",
		passive = {
			arpen = 50,
		},
	},
	["Corrosive Core"] = {
		itemId = 80674,
		category = "passive",
		passive = {
			hit = 1,
			arpen = 40,
		},
	},
	["Counterattack Lodestone"] = {
		itemId = 18537,
		category = "passive",
		passive = {
			ap = 22,
			parry = 1,
		},
	},
	["Drake Fang Talisman"] = {
		itemId = 19406,
		category = "passive",
		passive = {
			ap = 56,
			hit = 2,
			dodge = 1,
		},
	},
	["Rune of the Guard Captain"] = {
		itemId = 19120,
		category = "passive",
		passive = {
			hit = 1,
		},
	},
	["Taskmaster Whip"] = {
		itemId = 60715,
		category = "passive",
		passive = {
			haste = 2,
		},
	},
	["The Heart of Dreams"] = {
		itemId = 61194,
		category = "passive",
		passive = {
			crit = 2,
			haste = 2,
		},
	},
	["Whip of Encouragement"] = {
		itemId = 60501,
		category = "passive",
		passive = {
			haste = 3,
		},
	},
	["Mark of the Champion"] = {
		itemId = 23206,
		appliesAgainst = "Undead",
		category = "passive_conditional",
		passive = {
			ap = 150,
		},
	},
	["Seal of the Dawn"] = {
		itemId = 13209,
		appliesAgainst = "Undead",
		category = "passive_conditional",
		passive = {
			ap = 81,
		},
	},
	["Hand of Justice"] = {
		itemId = 11815,
		category = "passive_with_proc",
		proc = {
			chance = 2,
			type = "extra_attack",
			extraAttacks = 1,
		},
		passive = {
			ap = 20,
		},
	},
	["Darkmoon Card: Maelstrom"] = {
		itemId = 19289,
		category = "proc",
		proc = {
			chance = 2,
			type = "magic_damage",
			damage = 250,
		},
	},
	["Heart of Wyrmthalak"] = {
		itemId = 22321,
		category = "proc",
		proc = {
			chance = 2,
			type = "magic_damage",
			damage = 165,
		},
	},
	["Vial of Potent Venoms"] = {
		itemId = 61243,
		category = "proc",
		proc = {
			type = "venom_dot",
			chance = 50,
			duration = 12,
			tickInterval = 3,
			tickDamage = 30,
			maxStacks = 2,
		},
	},
}
